# Generated by Django 5.2.13 on 2026-05-02 02:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("life_admin", "0002_accountmodel_transactionmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactionmodel",
            name="is_base_salary",
            field=models.BooleanField(default=False),
        ),
    ]
