# Generated by Django 5.2.13 on 2026-05-03 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life_admin', '0005_savingsgoalmodel_budgetplanmodel_planneditemmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsdepositmodel',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savingsgoalmodel',
            name='expected_monthly_contribution',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
