# Generated by Django 5.2.13 on 2026-05-16 02:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life_admin', '0006_savingsdepositmodel_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetTokenModel',
            fields=[
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reset_tokens', to='life_admin.usermodel')),
            ],
            options={
                'db_table': 'password_reset_tokens',
            },
        ),
        migrations.DeleteModel(
            name='AppointmentModel',
        ),
        migrations.RemoveField(
            model_name='interactionmodel',
            name='contact',
        ),
        migrations.DeleteModel(
            name='DocumentModel',
        ),
        migrations.DeleteModel(
            name='ContactModel',
        ),
        migrations.DeleteModel(
            name='InteractionModel',
        ),
    ]
