# Generated by Django 5.2.13 on 2026-05-17 23:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life_admin', '0011_exchange_rates_recurring_balance_cache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringtransactionmodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userexchangeratemodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
